# Generated by Django 3.0.3 on 2020-03-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='image',
            new_name='picture',
        ),
    ]
