# Generated by Django 3.0.3 on 2020-04-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='principan',
            new_name='principal',
        ),
    ]
